# Generated by Django 5.1.7 on 2025-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing')], max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField()),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('employees_count', models.IntegerField()),
            ],
        ),
    ]
